Fixed the failing test for debugging
failing log snippet:
FAILED tests/test_counter.py::TestCounterEndpoints::test_failing_test - assert (1 + 1) == 1
========================= 1 failed, 23 passed in 0.36s =========================
Error: Process completed with exit code 1.

Root cause is that the test will always assert an error

Fix summary:
Editied the test to never assert an error